import { useState, useEffect, useCallback } from 'react'
import { movimentacoesService, categoriasService } from '../services/api'
import { format, parseISO } from 'date-fns'
import { ptBR } from 'date-fns/locale'
import { Plus, Pencil, Trash2, X, TrendingUp, TrendingDown, Search, Repeat } from 'lucide-react'
import './MovimentacoesPage.css'

const initForm = { tipo:'Despesa', valor:'', categoria:'', descricao:'', data_movimentacao: format(new Date(), "yyyy-MM-dd'T'HH:mm"), recorrente:false, frequencia:'Mensal', proxima_data_lancamento:'' }

export default function MovimentacoesPage() {
  const [movs, setMovs] = useState([]), [categorias, setCategorias] = useState([])
  const [loading, setLoading] = useState(true), [showModal, setShowModal] = useState(false), [editing, setEditing] = useState(null)
  const [form, setForm] = useState(initForm), [saving, setSaving] = useState(false)
  const [filters, setFilters] = useState({ mes:'', ano:'', tipo:'', categoria:'' }), [search, setSearch] = useState(''), [deleteConfirm, setDeleteConfirm] = useState(null), [msg, setMsg] = useState('')
  const load = useCallback(async () => { setLoading(true); try { const params={}; Object.entries(filters).forEach(([k,v])=>{ if(v) params[k]=v }); const res=await movimentacoesService.listar(params); setMovs(res.data); const cats=await categoriasService.listar(); setCategorias(cats.data) } finally { setLoading(false) } }, [filters])
  useEffect(()=>{ load() },[load])
  const openNew=()=>{setEditing(null);setForm(initForm);setShowModal(true)}
  const openEdit=(m)=>{setEditing(m);setForm({tipo:m.tipo,valor:String(m.valor),categoria:m.categoria,descricao:m.descricao||'',data_movimentacao:format(parseISO(m.data_movimentacao),"yyyy-MM-dd'T'HH:mm"),recorrente:!!m.recorrente,frequencia:m.frequencia||'Mensal',proxima_data_lancamento:m.proxima_data_lancamento?format(parseISO(m.proxima_data_lancamento),"yyyy-MM-dd'T'HH:mm"):''});setShowModal(true)}
  const handleSave=async(e)=>{e.preventDefault();setSaving(true);try{const payload={...form,valor:parseFloat(form.valor),data_movimentacao:new Date(form.data_movimentacao).toISOString(),recorrente:!!form.recorrente,frequencia:form.recorrente?form.frequencia:null,proxima_data_lancamento:form.recorrente && form.proxima_data_lancamento ? new Date(form.proxima_data_lancamento).toISOString():null}; if(editing) await movimentacoesService.atualizar(editing.id,payload); else await movimentacoesService.criar(payload); setShowModal(false); load()}catch(err){alert(err.response?.data?.detail||'Erro ao salvar movimentação')}finally{setSaving(false)}}
  const handleDelete=async(id)=>{await movimentacoesService.excluir(id);setDeleteConfirm(null);load()}
  const gerarRecorrentes=async()=>{const {data}=await movimentacoesService.gerarRecorrentes();setMsg(data.mensagem);load()}
  const fmt=(v)=>v?.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
  const cats=categorias.filter(c=>!c.tipo||c.tipo===form.tipo)
  const filtered=movs.filter(m=>!search||m.descricao?.toLowerCase().includes(search.toLowerCase())||m.categoria.toLowerCase().includes(search.toLowerCase()))
  const totalReceitas=movs.filter(m=>m.tipo==='Receita').reduce((s,m)=>s+m.valor,0), totalDespesas=movs.filter(m=>m.tipo==='Despesa').reduce((s,m)=>s+m.valor,0)
  return <div className="movs-page fade-in"><div className="page-header"><div><h1>Movimentações</h1><p className="page-desc">{movs.length} registro{movs.length!==1?'s':''} encontrado{movs.length!==1?'s':''}</p></div><div className="filters-header"><button className="btn-clear" onClick={gerarRecorrentes}><Repeat size={14}/> Lançar recorrentes</button><button className="btn-add" onClick={openNew}><Plus size={16}/> Nova movimentação</button></div></div>
    {msg && <div className="summary-item blue">{msg}</div>}
    <div className="movs-summary"><div className="summary-item green"><TrendingUp size={15}/><span>Receitas: <strong>{fmt(totalReceitas)}</strong></span></div><div className="summary-item red"><TrendingDown size={15}/><span>Despesas: <strong>{fmt(totalDespesas)}</strong></span></div><div className={`summary-item ${totalReceitas-totalDespesas>=0?'blue':'red'}`}><span>Saldo: <strong>{fmt(totalReceitas-totalDespesas)}</strong></span></div><div className="summary-item blue"><Repeat size={15}/><span>Recorrentes: <strong>{movs.filter(m=>m.recorrente).length}</strong></span></div></div>
    <div className="filters-row"><div className="search-box"><Search size={15}/><input placeholder="Buscar por descrição ou categoria..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={filters.mes} onChange={e=>setFilters(p=>({...p,mes:e.target.value}))}><option value="">Todos os meses</option>{Array.from({length:12},(_,i)=>i+1).map(m=><option key={m} value={m}>{format(new Date(2024,m-1,1),'MMMM',{locale:ptBR})}</option>)}</select><select value={filters.ano} onChange={e=>setFilters(p=>({...p,ano:e.target.value}))}><option value="">Todos os anos</option>{[2024,2025,2026].map(y=><option key={y}>{y}</option>)}</select><select value={filters.tipo} onChange={e=>setFilters(p=>({...p,tipo:e.target.value}))}><option value="">Todos os tipos</option><option value="Receita">Receitas</option><option value="Despesa">Despesas</option></select>{(filters.mes||filters.ano||filters.tipo||filters.categoria)&&<button className="btn-clear" onClick={()=>setFilters({mes:'',ano:'',tipo:'',categoria:''})}><X size={14}/> Limpar</button>}</div>
    {loading?<div className="table-loading"><div className="spinner"/></div>:filtered.length===0?<div className="empty-state"><TrendingUp size={40}/><p>Nenhuma movimentação encontrada</p><button className="btn-add" onClick={openNew}>Adicionar primeira movimentação</button></div>:<div className="table-card"><table className="movs-table"><thead><tr><th>Data</th><th>Tipo</th><th>Categoria</th><th>Descrição</th><th>Recorrência</th><th>Valor</th><th>Ações</th></tr></thead><tbody>{filtered.map(m=><tr key={m.id}><td className="date-cell">{format(parseISO(m.data_movimentacao),'dd/MM/yyyy')}</td><td><span className={`badge ${m.tipo==='Receita'?'badge-green':'badge-red'}`}>{m.tipo}</span></td><td>{m.categoria}</td><td className="desc-cell">{m.descricao||'—'}</td><td>{m.recorrente?<span className="badge badge-green"><Repeat size={12}/> {m.frequencia}</span>:'—'}</td><td className={`valor-cell ${m.tipo==='Receita'?'valor-green':'valor-red'}`}>{m.tipo==='Receita'?'+':'-'}{fmt(m.valor)}</td><td><div className="actions"><button className="btn-edit" onClick={()=>openEdit(m)}><Pencil size={14}/></button><button className="btn-del" onClick={()=>setDeleteConfirm(m.id)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div>}
    {showModal&&<div className="modal-overlay" onClick={()=>setShowModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><h3>{editing?'Editar':'Nova'} movimentação</h3><button className="btn-icon" onClick={()=>setShowModal(false)}><X size={18}/></button></div><form onSubmit={handleSave} className="modal-form"><div className="field"><label>Tipo</label><div className="tipo-toggle">{['Despesa','Receita'].map(t=><button type="button" key={t} className={`tipo-btn ${form.tipo===t?'active '+(t==='Receita'?'green':'red'):''}`} onClick={()=>setForm(p=>({...p,tipo:t,categoria:''}))}>{t==='Receita'?<TrendingUp size={14}/>:<TrendingDown size={14}/>} {t}</button>)}</div></div><div className="form-row"><div className="field"><label>Valor (R$)</label><input type="number" step="0.01" min="0.01" value={form.valor} onChange={e=>setForm(p=>({...p,valor:e.target.value}))} required/></div><div className="field"><label>Categoria</label><select value={form.categoria} onChange={e=>setForm(p=>({...p,categoria:e.target.value}))} required><option value="">Selecione...</option>{cats.map(c=><option key={c.id} value={c.nome}>{c.nome}</option>)}</select></div></div><div className="field"><label>Data</label><input type="datetime-local" value={form.data_movimentacao} onChange={e=>setForm(p=>({...p,data_movimentacao:e.target.value}))} required/></div><div className="field"><label>Descrição <span className="optional">(opcional)</span></label><input value={form.descricao} onChange={e=>setForm(p=>({...p,descricao:e.target.value}))} placeholder="Ex: aluguel, internet, salário..."/></div><div className="field recurring-box"><label><input type="checkbox" checked={form.recorrente} onChange={e=>setForm(p=>({...p,recorrente:e.target.checked}))}/> Movimentação recorrente</label></div>{form.recorrente&&<div className="form-row"><div className="field"><label>Frequência</label><select value={form.frequencia} onChange={e=>setForm(p=>({...p,frequencia:e.target.value}))}><option>Mensal</option><option>Semanal</option><option>Anual</option></select></div><div className="field"><label>Próxima data de lançamento</label><input type="datetime-local" value={form.proxima_data_lancamento} onChange={e=>setForm(p=>({...p,proxima_data_lancamento:e.target.value}))}/></div></div>}<div className="modal-actions"><button type="button" className="btn-cancel" onClick={()=>setShowModal(false)}>Cancelar</button><button type="submit" className="btn-save" disabled={saving}>{saving?'Salvando...':editing?'Salvar alterações':'Adicionar'}</button></div></form></div></div>}
    {deleteConfirm&&<div className="modal-overlay" onClick={()=>setDeleteConfirm(null)}><div className="modal modal-sm" onClick={e=>e.stopPropagation()}><div className="modal-header"><h3>Confirmar exclusão</h3><button className="btn-icon" onClick={()=>setDeleteConfirm(null)}><X size={18}/></button></div><p className="delete-msg">Tem certeza que deseja excluir esta movimentação?</p><div className="modal-actions"><button className="btn-cancel" onClick={()=>setDeleteConfirm(null)}>Cancelar</button><button className="btn-danger" onClick={()=>handleDelete(deleteConfirm)}>Excluir</button></div></div></div>}
  </div>
}
